function(magnus_target_embed_files TARGET)
    set(EMBED_CMAKE_C "${CMAKE_BINARY_DIR}/embed.cmake.cpp")
    set(EMBED_CMAKE_INCLUDE_DIR "${CMAKE_BINARY_DIR}/embed.cmake")
    set(EMBED_CMAKE_H "${CMAKE_BINARY_DIR}/embed.cmake/embed.cmake.h")
    add_custom_command(
        OUTPUT "${EMBED_CMAKE_C}" "${EMBED_CMAKE_H}"
        COMMAND "${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_SOURCE_DIR}/embed.cmake" -- "${EMBED_CMAKE_C}" "${EMBED_CMAKE_H}" ${ARGN}
        DEPENDS "embed.cmake" "${ARGN}"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    )
    target_include_directories("${TARGET}" PRIVATE "${EMBED_CMAKE_INCLUDE_DIR}")
    target_sources("${TARGET}" PRIVATE "${EMBED_CMAKE_C}" "${EMBED_CMAKE_H}")
endfunction()

if(DEFINED CMAKE_SCRIPT_MODE_FILE)
    set(ARG_NUM 1)

    while(ARG_NUM LESS CMAKE_ARGC)
        set(arg "${CMAKE_ARGV${ARG_NUM}}")
        math(EXPR ARG_NUM "${ARG_NUM}+1")
        if("${arg}" STREQUAL "--")
            break()
        endif()
    endwhile()

    set(EMBED_CMAKE_C "${CMAKE_ARGV${ARG_NUM}}")
    math(EXPR ARG_NUM "${ARG_NUM}+1")
    set(EMBED_CMAKE_H "${CMAKE_ARGV${ARG_NUM}}")
    math(EXPR ARG_NUM "${ARG_NUM}+1")
    file(WRITE "${EMBED_CMAKE_C}" "// generated by embed.cmake.\n// do not edit.\n#include \"embed.cmake.h\"\n\n")
    file(WRITE "${EMBED_CMAKE_H}" "// generated by embed.cmake.\n// do not edit.\n#pragma once\n\n")

    while(ARG_NUM LESS CMAKE_ARGC)
        set(file "${CMAKE_ARGV${ARG_NUM}}")
        cmake_path(GET file FILENAME file_stem)
        string(REGEX REPLACE "[^A-Za-z0-9_-]" "_" file_varname "${file_stem}")
        file(APPEND "${EMBED_CMAKE_H}" "// ${file}\nextern unsigned char const ${file_varname}[];\nextern unsigned const ${file_varname}_size;\n\n")

        file(READ "${file}" file_raw_hexes HEX)
        string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" SEPARATED_HEX ${file_raw_hexes})
        foreach (hex IN LISTS SEPARATED_HEX)
            string(APPEND file_formatted_hexes "0x${hex},")
        endforeach()

        # NOTE: we append a nul byte, so plain-text files can be used as C strings.
        file(APPEND "${EMBED_CMAKE_C}" "// ${file}\n")
        file(APPEND "${EMBED_CMAKE_C}" "unsigned char const ${file_varname}[] = {${file_formatted_hexes} 0x00};\n")
        file(APPEND "${EMBED_CMAKE_C}" "unsigned const ${file_varname}_size = sizeof(${file_varname}) - 1;\n\n")

        math(EXPR ARG_NUM "${ARG_NUM}+1")
    endwhile()
endif()
